refactor: add typescript [ECO-1027]
contentstack/contentstack-nuxtjs-starter-app pull request #25
Opened 2022-05-27 11:16 UTC by karantalapalli

refactor: add typescript [ECO-1027]

2022-05-30 06:20 UTC, abhishek305 reviewed
@karantalapalli also update the package.json version currently it's 1.3.0

2022-05-30 06:20 UTC, abhishek305 commented on pages/blog/indexPage.vue
> +    const recentBlog = [] as any
define types instead of any

2022-05-30 06:20 UTC, abhishek305 commented on pages/blog/indexPage.vue
> +        const element: any = document.getElementsByClassName('cslp-tooltip')
define type

2022-05-30 06:20 UTC, abhishek305 commented on pages/indexPage.vue
> +  async asyncData(req: any) {
same here define type

2022-05-30 06:20 UTC, abhishek305 commented on pages/indexPage.vue
> +      const element: any = document.getElementsByClassName('cslp-tooltip')
same as above comments

2022-05-30 06:20 UTC, abhishek305 commented on pages/blog/_blog.vue
> +  async asyncData(req: any) {
define type

2022-05-30 06:20 UTC, abhishek305 commented on pages/blog/_blog.vue
> +        const element: any = document.getElementsByClassName('cslp-tooltip')
here too

2022-05-30 07:25 UTC, Amitkanswal requested changes
hey @karantalapalli please update package.json version as well

2022-05-31 13:22 UTC, abhishek305 approved these changes

2022-05-31 13:26 UTC, Amitkanswal approved these changes

2022-06-06 07:25 UTC, merged